name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    environment: tlphong_docker_hub
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and Push the Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: tlphong/gpt-discord-bot:latest,yourusername/gpt-discord-bot:${{ github.run_number }}
        push: ${{ github.event_name != 'pull_request' }}  # Ensures image is pushed only on pushes to main, not on PRs

    - name: Print output image tag
      run: echo "The image was tagged as ${{ steps.docker_build.outputs.tags }}"

    - name: Logout from Docker
      if: always()  # This ensures logout even if the build fails
      run: docker logout
